# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
  
variables:
  SELENIUM_DEVICE_VERSION: latest
  SELENIUM_PLATFORM: Windows
  SELENIUM_PLATFORM_VERSION: 10
  RemoteBrowserDriverProvider: BrowserStack

jobs:
- job: ChromeTests
  variables:
    SELENIUM_BROWSER: Chrome
    SELENIUM_DEVICE: Chrome
  steps:
    - task: BrowserStackConfig@0
      inputs:
        BrowserStackServiceEndPoint: 'BrowserStack'

    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'verify'
        options: '-X -DENV=@test -Dcucumber.options="--tags @tmp"'
        testRunTitle: 'Chrome Selenium Smoke Tests'
    - task: CmdLine@2
      inputs:
        script: 'mv target/cucumber-json-report.json cucumber-json-report-chrome.json'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/cucumber-json-report-chrome.json'
        artifact: 'cucumber-chrome'
        publishLocation: 'pipeline'
          
- job: SafariTests
  variables:
    SELENIUM_BROWSER: Safari
    SELENIUM_DEVICE: Safari
    SELENIUM_DEVICE_VERSION: 13.1
    SELENIUM_PLATFORM: OS X
    SELENIUM_PLATFORM_VERSION: Catalina
  steps:
    - task: BrowserStackConfig@0
      inputs:
        BrowserStackServiceEndPoint: 'BrowserStack'
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'verify'
        options: '-X -DENV=@test -Dcucumber.options="--tags @tmp"'
        testRunTitle: 'Edge Selenium Smoke Tests'
    - task: CmdLine@2
      inputs:
        script: 'mv target/cucumber-json-report.json cucumber-json-report-safari.json'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/cucumber-json-report-safari.json'
        artifact: 'cucumber-safari'
        publishLocation: 'pipeline'

- job: Report
  dependsOn: [ChromeTests,SafariTests]
  steps:
  - task: DownloadPipelineArtifact@2
    inputs:
      buildType: 'current'
      artifactName: 'cucumber-chrome'
  - task: DownloadPipelineArtifact@2
    inputs:
      buildType: 'current'
      artifactName: 'cucumber-safari'


  - task: PublishCucumberReport@1
    inputs:
        jsonDir: '$(Pipeline.Workspace)'
        outputPath: '$(System.DefaultWorkingDirectory)'
        theme: 'bootstrap'
        reportSuiteAsScenarios: true
        name: 'Smoke Tests'
        title: 'Smoke Tests'